name: hus_app
description: "HUS - Audio Chat Social Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  
  # Authentication
  google_sign_in: ^6.1.6
  
  # Device Info
  device_info_plus: ^9.1.1
  
  # HTTP Requests
  http: ^1.1.2
  
  # Secure Storage
  flutter_secure_storage: ^9.0.0
  
  # State Management
  provider: ^6.1.1
  
  # URL Launcher for ads
  url_launcher: ^6.2.2
  
  # ZegoCloud SDK for audio rooms
  zego_uikit_prebuilt_live_audio_room: ^2.22.1
  zego_uikit: ^2.22.1
  zego_express_engine: ^3.14.5
  
  # Socket.io for real-time communication
  socket_io_client: ^2.0.3+1
  
  # UI Components
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

