workflows:
  android-apk:
    name: Android APK Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Set up Flutter
        script: |
          flutter channel stable
          flutter upgrade
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

