name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'نوع البناء'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        cache: true
        
    - name: Prepare project
      working-directory: frontend
      run: |
        flutter clean
        flutter pub get
        flutter pub upgrade
        
    - name: Build APK
      working-directory: frontend
      run: |
        if [ "${{ github.event.inputs.build_type }}" = "release" ]; then
          flutter build apk --release
        else
          flutter build apk --debug
        fi
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-${{ github.event.inputs.build_type }}-${{ github.run_number }}
        path: frontend/build/app/outputs/flutter-apk/*.apk
        retention-days: 30

